# Generated by Django 5.2.1 on 2025-06-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpage_tags_blogtagindexpage_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTagIndexPage',
        ),
    ]
