# Generated by Django 5.2.1 on 2025-06-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogindexpage_ai_translated_blogpage_ai_translated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Fréttasíða', 'verbose_name_plural': 'Fréttasíður'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Frétt', 'verbose_name_plural': 'Fréttir'},
        ),
    ]
