# Generated by Django 5.2.1 on 2025-05-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='event_type',
        ),
    ]
