# Generated by Django 5.2.1 on 2025-06-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventtagindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='eventtagindexpage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
