# Generated by Django 5.2.1 on 2025-06-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventpage_tags_eventtagindexpage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTag',
        ),
    ]
