# Generated by Django 5.2.1 on 2025-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_delete_eventtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTagIndexPage',
        ),
    ]
