# Generated by Django 5.2.1 on 2025-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_delete_eventtagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
    ]
