# Generated by Django 5.2.1 on 2025-06-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventindexpage_ai_translated_eventpage_ai_translated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventindexpage',
            options={'verbose_name': 'Viðburðasíða', 'verbose_name_plural': 'Viðburðasíður'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Viðburður', 'verbose_name_plural': 'Viðburðir'},
        ),
    ]
