# Generated by Django 5.2.1 on 2025-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titill')),
                ('description', models.TextField(verbose_name='Lýsing')),
                ('company_name', models.CharField(max_length=200, verbose_name='Fyrirtæki')),
                ('contact_name', models.CharField(max_length=120, verbose_name='Tengiliður')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Tengiliðapóstur')),
                ('other', models.TextField(blank=True, verbose_name='Annað')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auglýst verkefni',
                'verbose_name_plural': 'Auglýst verkefni',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveField(
            model_name='advertiseprojectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AdvertiseFormField',
        ),
        migrations.DeleteModel(
            name='AdvertiseProjectPage',
        ),
    ]
