# Generated by Django 5.2.1 on 2025-06-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_projectindexpage_projectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectad',
            name='project_page',
            field=models.ForeignKey(blank=True, help_text='Verkefnasíða sem búin var til úr þessari auglýsingu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.projectpage', verbose_name='Tengd verkefnasíða'),
        ),
    ]
