# Generated by Django 5.2.1 on 2025-06-04 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_projectad_project_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='leidbeinendur',
            field=models.ManyToManyField(blank=True, help_text='Starfsmenn sem hafa tekið að sér þetta verkefni', limit_choices_to={'groups__name': 'Starfsmenn'}, to=settings.AUTH_USER_MODEL, verbose_name='Leiðbeinendur'),
        ),
    ]
