# Generated by Django 5.2.1 on 2025-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_projectad_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectad',
            name='locale',
            field=models.CharField(choices=[('is', 'Íslenska'), ('en', 'English')], default='is', help_text='Tungumál auglýsingar þegar hún verður birt', max_length=10, verbose_name='Tungumál'),
        ),
    ]
