# Generated by Django 5.2.1 on 2025-06-04 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_alter_projectad_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectad',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Project advertisement', 'verbose_name_plural': 'Project advertisements'},
        ),
        migrations.AddField(
            model_name='projectad',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Viewed at'),
        ),
        migrations.AlterField(
            model_name='projectad',
            name='locale',
            field=models.CharField(choices=[('is', 'Icelandic'), ('en', 'English')], default='is', help_text='Tungumál auglýsingar þegar hún er birt', max_length=10, verbose_name='Tungumál'),
        ),
        migrations.AlterField(
            model_name='projectad',
            name='project_page',
            field=models.ForeignKey(blank=True, help_text='Project page created from this advertisement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='advertise.projectpage', verbose_name='Linked project page'),
        ),
    ]
