# Generated by Django 5.2.1 on 2025-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_projectpage_leidbeinendur'),
        ('advertise', '0007_alter_projectad_options_projectad_viewed_at_and_more'),
    ]

    operations = [
    ]
