# Generated by Django 5.2.1 on 2025-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_merge_20250604_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Verkefni'},
        ),
    ]
