# Generated by Django 5.2.1 on 2025-06-06 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_projectpage_selected_students_projectapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectad',
            name='requested_advisors',
            field=models.ManyToManyField(blank=True, help_text='Starfsmenn sem óskað er eftir til að vera leiðbeinendur verkefnis.', limit_choices_to={'groups__name': 'Starfsmenn'}, related_name='requested_projects', to=settings.AUTH_USER_MODEL, verbose_name='Óskir um leiðbeinendur'),
        ),
    ]
