# Generated by Django 5.2.1 on 2025-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_alter_projectad_requested_advisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectad',
            name='time_limit',
            field=models.DateField(blank=True, help_text='Umsóknarfrestur verkefnisins. Skildu eftir tómt ef verkefnið á að vera ávallt sýnilegt.', null=True, verbose_name='Umsóknarfrestur verkefnis'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='time_limit',
            field=models.DateField(blank=True, help_text='Dagsetning þegar verkefnið hverfur af vefnum. Skildu eftir tómt ef verkefnið á að vera ávallt sýnilegt.', null=True, verbose_name='Tímamörk verkefnis'),
        ),
    ]
