# Generated by Django 5.2.1 on 2025-06-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0013_projectad_time_limit_projectpage_time_limit'),
        ('advertise', '0013_projectpage_ai_translated'),
    ]

    operations = [
    ]
