# Generated by Django 5.2.1 on 2025-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0014_merge_20250611_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='time_limit',
            field=models.DateField(blank=True, help_text='Umsóknarfrestur fyrir nemendur og starfsmenn. Verkefnið verður ekki sýnilegt að honum liðnum.', null=True, verbose_name='Umsóknarfrestur verkefnis'),
        ),
    ]
