# Generated by Django 5.2.1 on 2025-06-11 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0015_alter_projectpage_time_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProjectAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('verification_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pending Project Advertisement',
                'verbose_name_plural': 'Pending Project Advertisements',
            },
        ),
    ]
