# Generated by Django 5.2.1 on 2025-06-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0016_pendingprojectad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectindexpage',
            options={'verbose_name': 'Verkefnasíða', 'verbose_name_plural': 'Verkefnasíður'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Verkefni', 'verbose_name_plural': 'Verkefni'},
        ),
    ]
