# Generated by Django 5.2.1 on 2025-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0017_alter_projectindexpage_options_and_more'),
        ('base', '0012_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectad',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Veljið tögg sem lýsa þessu verkefni', to='base.tag', verbose_name='Verkefnistögg'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tögg sem lýsa þessu verkefni', to='base.tag', verbose_name='Verkefnistögg'),
        ),
    ]
