# Generated by Django 5.2.1 on 2025-06-13 11:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0018_projectad_tags_projectpage_tags'),
        ('base', '0012_alter_tag_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectad',
            name='tags',
        ),
        migrations.CreateModel(
            name='ProjectAdTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='advertise.projectad')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Project Ad Tag',
                'verbose_name_plural': 'Project Ad Tags',
            },
        ),
    ]
