# Generated by Django 5.2.1 on 2025-06-13 14:54

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0019_remove_projectad_tags_projectadtaggeditem'),
        ('base', '0012_alter_tag_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
        migrations.CreateModel(
            name='ProjectPageTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tagged_items', to='advertise.projectpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Project Page Tag',
                'verbose_name_plural': 'Project Page Tags',
            },
        ),
    ]
