# Generated by Django 5.2.1 on 2025-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_supporterspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
        migrations.AddField(
            model_name='supporterspage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
    ]
