# Generated by Django 5.2.1 on 2025-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
