# Generated by Django 5.2.1 on 2025-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_personpage_personal_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
