# Generated by Django 5.2.1 on 2025-06-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_personpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpage',
            name='tags',
        ),
    ]
