# Generated by Django 5.2.1 on 2025-06-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_tag_options_tag_color'),
        ('people', '0007_remove_personpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select tags that apply to this person', to='base.tag'),
        ),
    ]
