# Generated by Django 5.2.1 on 2025-06-10 15:31

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_tag_options_tag_color'),
        ('people', '0008_personpage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select tags that apply to this person', to='base.tag'),
        ),
    ]
