# Generated by Django 5.2.1 on 2025-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_personpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentindexpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
        migrations.AddField(
            model_name='peopleindexpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='ai_translated',
            field=models.BooleanField(default=False, help_text='This page was translated using AI'),
        ),
    ]
