# Generated by Django 5.2.1 on 2025-06-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_departmentindexpage_ai_translated_and_more'),
        ('people', '0010_remove_personpage_tags'),
    ]

    operations = [
    ]
