# Generated by Django 5.2.1 on 2025-06-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_merge_20250611_1125'),
        ('people', '0011_merge_20250611_1131'),
    ]

    operations = [
    ]
