# Generated by Django 5.2.1 on 2025-06-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_departmentindexpage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentIndexPage',
        ),
    ]
