# Generated by Django 5.2.1 on 2025-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formpage_formfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name': 'Footer text', 'verbose_name_plural': 'Footer text'},
        ),
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='translation_key',
        ),
    ]
