# Generated by Django 5.2.1 on 2025-05-26 11:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_footertext_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
