# Generated by Django 5.2.1 on 2025-05-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_formpage_page_ptr_delete_formfield_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationSettings',
        ),
    ]
