# Generated by Django 5.2.1 on 2025-06-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_taggeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterText',
        ),
    ]
