# Generated by Django 5.2.1 on 2025-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_footertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#3498db', help_text='Choose a color for this tag (hex format: #RRGGBB)', max_length=7),
        ),
    ]
