# Generated by Django 5.2.1 on 2025-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_tag_options_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name_en']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(default='tobechanged', help_text='Tag name in English', max_length=255, verbose_name='Name (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name_is',
            field=models.CharField(default='verdurbreytt', help_text='Tag name in Icelandic', max_length=255, verbose_name='Name (Icelandic)'),
            preserve_default=False,
        ),
    ]
