# Generated by Django 5.2.1 on 2025-06-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_tag_options_remove_tag_name_tag_name_en_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name_is', 'name_en')},
        ),
    ]
